AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  BabaMuskBot

  SAM Template for BabaMuskBot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 90

Parameters:
  TOKEN: #Telegram Token
    Type: String
  POLYGON_KEY:
    Type: String

Resources:
  BabaMuskFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: baba_musk_bot/
      Handler: app.webhook
      Runtime: python3.8
      Policies:
        AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TELEGRAM_TOKEN: !Ref TOKEN
          POLYGON_API_KEY: !Ref POLYGON_KEY
      Events:
        BabaMusk:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /webhook
            Method: post

#  BabaMuskSentMessageStore:
#    Type: AWS::Serverless::SimpleTable
#    Properties:
#      TableName: BabaMuskSentMessageStore
#      PrimaryKey:
#        Name: chat_message_id
#        Type: String
#
#  BabaMuskScruber:
#    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#    Properties:
#      CodeUri: baba_musk_bot/
#      Handler: scrub.run
#      Runtime: python3.8
#      Events:
#        HourlyCleanEvent:
#          Type: Schedule
#          Properties:
#            Schedule: cron(0 * * * ? *)

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BabaMuskApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/"
  BabaMuskFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt BabaMuskFunction.Arn
  BabaMuskFunctionIamRole:
    Description: "Implicit IAM Role created for BabaMusk function"
    Value: !GetAtt BabaMuskFunctionRole.Arn
