# This is a basic workflow to help you get started with Actions

name: SAM Validate, Build, Test, Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sam-validate-build-test-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies with Apt Get
        run: |
          sudo apt-get update
          sudo apt-get install python3.8 jq -y
      - name: Install Pip Dependencies for CI
        run: |
          pip3 install -r baba_musk_bot/requirements.txt
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: SAM Validate
        run: |
          sam validate
      - name: Configure variables
        shell: bash
        id: vars
        env:
          REPO: ${{ github.repository }}
          HASH: ${{ github.sha }}
          REF: ${{ github.ref }}
        run: |
          # Set variables
          BRANCH=${REF#refs/heads/}
          REPOSITORY=`echo $REPO | tr "/" "-"`
          ENVIRONMENT=$BRANCH-$REPOSITORY-${{ secrets.AWS_REGION }}
          TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
          # In this step we are setting variables and persistenting them
          # into the environment so that they can be utilized in other steps
          echo "::set-output name=branch::$BRANCH"
          echo "::set-output name=repository::$REPOSITORY"
          echo "::set-output name=environment::$ENVIRONMENT"
          # Output variables to ensure their values are set correctly when ran
          echo "The region is ${{ secrets.AWS_REGION }}"
          echo "The repository is $REPOSITORY"
          echo "The environment is $ENVIRONMENT"
          echo "The branch is $BRANCH"
          echo "TELEGRAM_TOKEN is set."
      - name: SAM Build
        run: |
          sam build
      - name: Run tests
        run: |
          export TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
          export AWS_SAM_STACK_NAME=BabaMuskBot
          python3 -m pytest --cov=baba_musk_bot tests/
      - name: SAM Deploy
        run: |
          sam deploy --template-file .aws-sam/build/template.yaml \
            --stack-name BabaMuskBot \
            --resolve-s3 \
            --config-file samconfig.toml \
            --parameter-overrides \
              'TOKEN=${{ secrets.TELEGRAM_TOKEN }}' \
            --capabilities CAPABILITY_IAM
